--##################
--## MY PROGRAMS ###
--##################

-- Set programs that you use
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local terminal = "alacritty"
local fileManager = "nemo"
local menu = "noctalia-shell ipc call launcher toggle"

--############
--## INPUT ###
--############

-- https://wiki.hyprland.org/Configuring/Variables/#input

local mainMod = "SUPER"

hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exec_cmd("cool-retro-term --fullscreen"))
hl.bind(mainMod .. " + TAB", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exit())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("chromium"))
hl.bind(mainMod .. " + U", hl.dsp.exec_cmd("qimgv ~/Pictures/black.jpg"))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + code:49", hl.dsp.exec_cmd("noctalia-shell ipc call controlCenter toggle"))

hl.bind("CTRL + SHIFT + ESCAPE", hl.dsp.exec_cmd("[float] alacritty -e btop"))

hl.bind(mainMod .. " + Z", hl.dsp.pass({ window = "class:^(com\\.obsproject\\.Studio)$" }))
-- TODO: manual review on line 65 — no mapping for dispatcher "class:^(com\\.obsproject\\.Studio)$"
-- hl.bind("CTRL + , pass", hl.dsp.class___com__obsproject__Studio__())

-- TODO: manual review on line 68 — no mapping for dispatcher "class:^(io.github.radiolamp.mangojuice)$"
-- hl.bind("SHIFT + , pass", hl.dsp.class___io_github_radiolamp_mangojuice__())

hl.bind("SHIFT + END", hl.dsp.pass({ window = "^(vesktop)$" }))

hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("./Scripts/stream.sh"))

hl.bind(mainMod .. " + SHIFT + Print", hl.dsp.exec_cmd("grim -g \"$(slurp -d)\" \"$HOME/Pictures/Screenshots/$(date '+%y%m%d_%H-%M-%S').png\""))
hl.bind("Print", hl.dsp.exec_cmd("grim -o DP-1 \"$HOME/Pictures/Screenshots/$(date '+%y%m%d_%H-%M-%S').png\""))

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())
hl.config({
    input = {
        kb_layout = "us,es",
        kb_variant = "",
        kb_model = "",
        kb_options = "grp:alt_shift_toggle",
        kb_rules = "",
        follow_mouse = 2,
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
        -- Removes Mouse Acceleration But May Cause Curson Desyncronization
        --force_no_accel = true
        accel_profile = "flat",
        natural_scroll = false,
        --scroll_button =
        touchpad = {
            natural_scroll = false,
        },
    },
    --###################
    --## KEYBINDINGSS ###
    --###################
    -- Sets The Super Key
    -- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
    --bind = $mainMod, J, rotatesplit, # dwindle
    --Task Manager
    -- Global Keybinds
    -- OBS
    -- Mangohud
    -- Discord
    --Stream Setup Bind
    -- Grim and Slurp
    -- Move focus with mainMod + arrow keys
    -- Switch workspaces with mainMod + [0-9]
    -- Move active window to a workspace with mainMod + SHIFT + [0-9]
    -- Example special workspace (scratchpad)
    -- Scroll through existing workspaces with mainMod + scroll
    --bind = $mainMod, mouse:275, workspace, e+1
    --bind = $mainMod, mouse:276, workspace, e-1
    -- Move/resize windows with mainMod + LMB/RMB and dragging
})

