--####################
--## LOOK AND FEEL ###
--####################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 2,
    bezier = "myBezier",
    style = "popin",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 1,
    bezier = "default",
    style = "popin",
})
hl.animation({
    leaf = "windowsIn",
    enabled = false,
    speed = 0,
    bezier = "default",
    style = "popin",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 8,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = false,
    speed = 3,
    bezier = "default",
    style = "fadein",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.75,
    bezier = "default",
    style = "fade",
})

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 15,
        border_size = 0,
        col = {
            active_border = "rgba(fbfaf7cc)",
            inactive_border = "rgba(595959aa)",
        },
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Turn on to reduce/fix jitter or stutter in games
        allow_tearing = false,
        -- Window Tiling Layout
        layout = "dwindle",
    },
    decoration = {
        rounding = 8,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        -- Shadow behind windows
        shadow = {
            enabled = true,
            range = 10,
            render_power = 5,
            color = "rgba(1a1a1aee)",
        },
        -- window background blur
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
    -- Animations
    animations = {
        enabled = true,
        --windowrule = noborder, focus:0
        --windowrulev2 = noborder, focus:1
    },
    -- Dwindle Layout Settings
    dwindle = {
        preserve_split = true, -- You probably want this
    },
    -- Master Layout Settings
    master = {
        new_status = "master",
    },
    ecosystem = {
        no_update_news = true,
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#misc
    misc = {
        force_default_wallpaper = 0, -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = true, -- If true disables the random hyprland logo / anime girl background. :(
        --vfr = true
        -- Renders before monitor displays fram to reduce latency but buggy
        --render_ahead_of_time = true
    },
})

