--################
--## AUTOSTART ###
--################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

--exec-once = swww-daemon & swww init & swww img
--exec-once = flatpak run com.spotify.Client
--exec-once = openrgb

--############################
--## ENVIRONMENT VARIABLES ###
--############################

--env = XCURSOR_SIZE,28
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "NotwaitaBlack")
hl.env("GDK_SCALE", "1.1")
--env = SDL_VIDEODRIVER,wayland
--env = GTK_THEME, Raleigh-dark
--env = ELECTRON_OZONE_PLATFORM_HINT,auto

hl.on("hyprland.start", function()
    hl.exec_cmd("noctalia-shell")
    hl.exec_cmd("dunst")
    hl.exec_cmd("steam")
    hl.exec_cmd("xremap ~/NathOS/dotfiles/homeprint.yml --device '2.4G Wireless Keyboard'")
end)

